name: alphazero
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - annotated-types==0.7.0
    - anyio==4.9.0
    - attrs==25.3.0
    - blinker==1.9.0
    - certifi==2025.7.14
    - charset-normalizer==3.4.2
    - click==8.2.1
    - flask==3.1.1
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - httpx-sse==0.4.1
    - idna==3.10
    - itsdangerous==2.2.0
    - jinja2==3.1.6
    - jsonschema==4.25.0
    - jsonschema-specifications==2025.4.1
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - mcp==1.12.0
    - mdurl==0.1.2
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pydantic-settings==2.10.1
    - pygments==2.19.2
    - python-dotenv==1.1.1
    - python-multipart==0.0.20
    - referencing==0.36.2
    - requests==2.32.4
    - rich==14.0.0
    - rpds-py==0.26.0
    - setuptools==78.1.1
    - shellingham==1.5.4
    - sniffio==1.3.1
    - sse-starlette==2.4.1
    - starlette==0.47.2
    - typer==0.16.0
    - typing-extensions==4.14.1
    - typing-inspection==0.4.1
    - urllib3==2.5.0
    - uvicorn==0.35.0
    - werkzeug==3.1.3
    - wheel==0.45.1
